version: "3"

services:
  db:
    image: mongo:4.2.3
    restart: always
    container_name: mongoDB_streaming
    ports:
      - "27016:27017"
    env_file: .env
    environment:
      TZ: Asia/Seoul
      # MongoDB 계정 및 패스워드 설정 옵션
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

